#
# imb.ini — Intel MPI Benchmarks
#

[ASIS TestGet:IMB]
parent = MiddlewareBuild:OMPI
plugin = Git
url = https://github.com/intel/mpi-benchmarks

[ASIS TestBuild:IMB]
parent = TestGet:IMB
middleware = MiddlewareBuild:OMPI
plugin = Shell
command = CC=mpicc CXX=mpicxx make -j @JOBS@ IMB-MPI1

[TestRun:IMB]
parent = TestBuild:IMB
plugin = OpenMPI
timeout = 120
test_list = IMB-MPI1
