#
# Intel MPI test suite from the private open-mpi/ompi-tests repo.
# Requires SSH access to git@github.com:open-mpi/ompi-tests
#

[ASIS TestGet:Intel]
parent = MiddlewareBuild:OMPI
plugin = Git
url = git@github.com:open-mpi/ompi-tests
subdir = intel_tests

[TestBuild:Intel]
parent = TestGet:Intel
middleware = MiddlewareBuild:OMPI
merge_stdout_stderr = 1
stderr_save_lines = 100
make_options = -j @JOBS@ jcompile FILE=all_tests_no_perf_c

[TestRun:Intel]
parent = TestBuild:Intel
plugin = OpenMPI
timeout = 120
test_dir = src
stdout_save_lines = 100
stderr_save_lines = 100
