#
# mpich.ini — MPICH test suite run against Open MPI
#

[ASIS TestGet:MPICH]
parent = MiddlewareBuild:OMPI
plugin = Git
url = https://github.com/pmodels/mpich

[TestBuild:MPICH]
parent = TestGet:MPICH
middleware = MiddlewareBuild:OMPI
plugin = Shell
command = sh @TESTS_DIR@/mpich-build.sh @JOBS@

[TestRun:MPICH]
parent = TestBuild:MPICH
plugin = OpenMPI
timeout = 600
test_dir = "test/mpi/pt2pt, test/mpi/collective, test/mpi/comm, test/mpi/datatype, test/mpi/init"
