#
# osu.ini — OSU Micro-Benchmarks
#

[ASIS TestGet:OSU]
parent = MiddlewareBuild:OMPI
plugin = Git
url = https://github.com/ULHPC/osu-micro-benchmarks

[ASIS TestBuild:OSU]
parent = TestGet:OSU
middleware = MiddlewareBuild:OMPI
plugin = Autotools
configure_options = CC=mpicc CXX=mpicxx
make_options = -j @JOBS@ install

[TestRun:OSU]
parent = TestBuild:OSU
plugin = OpenMPI
timeout = 120
test_dir = "mpi/pt2pt, mpi/collective"
test_list = osu_latency, osu_bw, osu_allreduce, osu_barrier
