#
# smoke.ini — basic MPI smoke tests
#
# Tests: hello_world, get_version, init_finalize, comm_info, bcast
#

[ASIS TestGet:Smoke]
parent = MiddlewareBuild:OMPI
plugin = Copytree
src = @TESTS_DIR@/smoke

[TestBuild:Smoke]
parent = TestGet:Smoke
middleware = MiddlewareBuild:OMPI
make_options = -j @JOBS@

[TestRun:Smoke]
parent = TestBuild:Smoke
plugin = OpenMPI
timeout = 30
test_list = hello_world, get_version, init_finalize, comm_info, bcast
